import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const root=path.dirname(fileURLToPath(import.meta.url));
const require=createRequire('C:/Users/Oviks/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/runtime.cjs');
const {chromium}=require('playwright');
const base=process.env.PORTFOLIO_PREVIEW_URL || 'http://127.0.0.1:4392',key='sideb.demo.bag.v1';
const browser=await chromium.launch({headless:true});
const report={date:'2026-10-03',environment:'Bundled Playwright / headless Chromium / Windows',scope:'Isolated local SIDE B case and HTML storefront. No live Shopify or device verification.',checks:[],viewports:[],errors:[],screenshots:[]};
const check=(name,detail)=>report.checks.push({name,result:'pass',detail});
const screenshot=async(page,name,fullPage=false)=>{await page.screenshot({path:path.join(root,'evidence',name),fullPage});report.screenshots.push(name)};
const watch=page=>{page.on('pageerror',e=>report.errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error')report.errors.push(msg.text())})};
async function loaded(page){await page.evaluate(()=>document.fonts.ready);for(const image of await page.locator('img:not(dialog img)').all()){await image.scrollIntoViewIfNeeded();await image.evaluate(img=>img.decode())}await page.evaluate(()=>scrollTo(0,0))}
async function links(page){
 const refs=await page.locator('a[href],link[href],script[src]').evaluateAll(nodes=>nodes.map(el=>el.getAttribute('href')||el.getAttribute('src')));
 for(const ref of new Set(refs)){
  if(/^(https?:|data:|mailto:)/.test(ref))continue;
  const url=new URL(ref,page.url());
  if(url.pathname===new URL(page.url()).pathname&&url.hash){assert.ok(await page.locator(url.hash).count(),`Missing fragment ${ref}`);continue}
  const response=await page.request.get(url.href.split('#')[0]);assert.equal(response.status(),200,`Broken local reference ${ref}`);
  if(url.hash)assert.ok((await response.text()).includes(`id="${url.hash.slice(1)}"`),`Missing linked fragment ${ref}`);
 }
}
try{
 for(const [width,height] of [[1440,1000],[320,740],[390,844],[768,1024],[568,320]]){
  for(const route of ['side-b-demo.html','side-b.html']){
   const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1});const page=await context.newPage();watch(page);
   await page.goto(`${base}/${route}`);await loaded(page);await links(page);
   const metrics=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,images:[...document.images].filter(img=>!img.closest('dialog')).map(img=>({src:img.getAttribute('src'),loaded:img.complete&&img.naturalWidth>0})),ids:[...document.querySelectorAll('[id]')].map(el=>el.id),smallTargets:[...document.querySelectorAll('button,input,select')].filter(el=>!el.closest('dialog')&&el.getClientRects().length).map(el=>({name:el.getAttribute('aria-label')||el.textContent.trim(),height:el.getBoundingClientRect().height,width:el.getBoundingClientRect().width})).filter(r=>r.height<44)}));
   assert.ok(metrics.scrollWidth<=width,`${route} overflow at ${width}`);assert.ok(metrics.images.every(img=>img.loaded));assert.equal(metrics.ids.length,new Set(metrics.ids).size);assert.equal(metrics.smallTargets.length,0);
   report.viewports.push({route,width,height,horizontalOverflow:false,imagesLoaded:metrics.images.length,interactiveControlsAtLeast44pxHigh:true});
   if(width===1440||width===390)await screenshot(page,`side-b-${route==='side-b.html'?'case':'demo'}-${width===1440?'desktop':'mobile'}.jpg`,true);
   if(route==='side-b-demo.html'&&width!==1440){await page.locator('[data-product="night"]').first().click();await page.locator('#sideb-product-image').evaluate(img=>img.decode());assert.ok(await page.evaluate(()=>{const d=document.querySelector('#sideb-product-dialog');return d.scrollWidth<=d.clientWidth+1}));await page.selectOption('#sideb-format','standard');await page.fill('#sideb-quantity','1');await page.locator('#sideb-product-form button[type=submit]').click();assert.match(await page.locator('#sideb-product-status').textContent(),/Added 1/);await page.click('#sideb-product-view-bag');assert.equal(await page.locator('#sideb-bag-total').textContent(),'£28.00');assert.equal(await page.locator('#sideb-bag-items article').count(),1);assert.equal(await page.evaluate(()=>document.activeElement.closest('dialog')?.id),'sideb-bag-dialog');if(width===390)await screenshot(page,'side-b-bag-mobile.jpg');if(width===568)await screenshot(page,'side-b-bag-short-landscape.jpg');await page.keyboard.press('Escape');}
   await context.close();
  }
 }
 check('Responsive layout, loaded lazy images, local links and targets','Case and demo at 1440×1000, 320×740, 390×844, 768×1024 and 568×320; no horizontal overflow or broken local resources. Non-dialog buttons/inputs/selects are at least 44px high.');
 const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();watch(page);await page.goto(base+'/side-b-demo.html');await loaded(page);
 await page.click('[data-filter="Ambient"]');assert.equal(await page.locator('.sideb-record:visible').count(),1);assert.equal(await page.locator('.sideb-record:visible h3').textContent(),'Soft Static');assert.equal(await page.locator('#sideb-filter-status').textContent(),'1 record / Ambient');assert.equal(await page.locator('.sideb-record[hidden] button').evaluateAll(nodes=>nodes.filter(el=>el.getClientRects().length).length),0);await page.click('[data-filter="Jazz"]');assert.equal(await page.locator('.sideb-record:visible h3').textContent(),'After Hours');await page.click('[data-filter="Electronic"]');assert.equal(await page.locator('.sideb-record:visible h3').textContent(),'Night Index');await page.click('[data-filter="all"]');assert.equal(await page.locator('.sideb-record:visible').count(),3);check('Meaningful genre filtering','Correct record shown for each genre; selected state and live record count; hidden cards have no rendered/focusable controls.');
 await page.click('#sideb-bag-open');assert.match(await page.locator('#sideb-bag-items').textContent(),/Your bag is empty/);assert.equal(await page.locator('#sideb-bag-total').textContent(),'£0.00');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'sideb-bag-open');check('Empty bag and Escape','Empty explanation, zero subtotal, native modal dismissal and opener focus restoration.');
 const opener=page.locator('[data-product="night"]').first();await opener.focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Close record details');await page.keyboard.press('Shift+Tab');assert.ok(await page.evaluate(()=>document.activeElement.closest('dialog')?.id==='sideb-product-dialog'));await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Close record details');
 await page.click('#sideb-gallery-detail');assert.equal(await page.locator('#sideb-gallery-detail').getAttribute('aria-pressed'),'true');assert.match(await page.locator('#sideb-product-image').getAttribute('src'),/night-detail/);await page.locator('#sideb-product-image').evaluate(img=>img.decode());await page.click('#sideb-gallery-front');
 await page.locator('#sideb-product-form button[type=submit]').click();assert.match(await page.locator('#sideb-product-status').textContent(),/Choose a format/);assert.equal(await page.evaluate(()=>document.activeElement.id),'sideb-format');assert.equal(await page.locator('#sideb-product-status').evaluate(el=>el.closest('dialog').id),'sideb-product-dialog');
 await page.selectOption('#sideb-format','standard');for(const value of ['','0','-1','1.5','10']){await page.fill('#sideb-quantity',value);await page.locator('#sideb-product-form button[type=submit]').click();assert.match(await page.locator('#sideb-product-status').textContent(),/whole quantity/);assert.equal(await page.locator('#sideb-count').textContent(),'0')}
 await page.fill('#sideb-quantity','2');await page.locator('#sideb-product-form button[type=submit]').click();assert.equal(await page.locator('#sideb-count').textContent(),'2');assert.match(await page.locator('#sideb-product-status').textContent(),/Added 2/);await page.selectOption('#sideb-format','art');await page.fill('#sideb-quantity','1');await page.locator('#sideb-product-form button[type=submit]').click();assert.equal(await page.locator('#sideb-count').textContent(),'3');await screenshot(page,'side-b-product-desktop.jpg');
 await page.click('#sideb-product-view-bag');assert.equal(await page.locator('#sideb-bag-items article').count(),2);assert.equal(await page.locator('#sideb-bag-total').textContent(),'£92.00');assert.ok(await page.evaluate(()=>document.body.classList.contains('sideb-dialog-open')));check('Format validation, quantity validation and edition separation','Unselected format and quantities blank/0/negative/fractional/10 rejected; 2 LPs at £28 plus 1 art edition at £36 produce 3 items and £92.00 across two distinct lines.');
 await page.fill('#sideb-qty-night-standard','0');await page.getByRole('button',{name:'Update Night Index, Black vinyl LP quantity'}).click();assert.match(await page.locator('#sideb-bag-status').textContent(),/whole quantity/);assert.equal(await page.locator('#sideb-bag-total').textContent(),'£92.00');await page.fill('#sideb-qty-night-standard','3');await page.getByRole('button',{name:'Update Night Index, Black vinyl LP quantity'}).click();assert.equal(await page.locator('#sideb-bag-total').textContent(),'£120.00');assert.equal(await page.evaluate(()=>document.activeElement.id),'sideb-qty-night-standard');assert.match(await page.locator('#sideb-bag-status').textContent(),/Updated/);await screenshot(page,'side-b-bag-desktop.jpg');
 await page.reload();await page.click('#sideb-bag-open');assert.equal(await page.locator('#sideb-bag-total').textContent(),'£120.00');assert.equal(await page.locator('#sideb-count').textContent(),'4');await page.getByRole('button',{name:'Remove Night Index, LP + cover print',exact:true}).click();assert.equal(await page.locator('#sideb-bag-total').textContent(),'£84.00');await page.getByRole('button',{name:'Remove Night Index, Black vinyl LP',exact:true}).click();assert.equal(await page.locator('#sideb-bag-total').textContent(),'£0.00');assert.match(await page.locator('#sideb-bag-status').textContent(),/Your bag is empty/);await page.keyboard.press('Escape');check('Bag updates, persistence and removal','Invalid update retains £92; valid update yields £120 and keeps field focus; reload preserves bag; removing editions reaches £84 then empty £0 with feedback inside bag dialog.');
 await opener.click();await page.selectOption('#sideb-format','standard');await page.fill('#sideb-quantity','9');await page.locator('#sideb-product-form button[type=submit]').click();await page.locator('#sideb-product-form button[type=submit]').click();assert.match(await page.locator('#sideb-product-status').textContent(),/up to 9/);assert.equal(await page.locator('#sideb-count').textContent(),'9');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Explore Night Index by Mara Circuit');check('Per-edition maximum and keyboard restoration','Duplicate adds cannot exceed 9 of the same edition. Escape restores the record opener. Shift+Tab/Tab wrap within the modal.');
 await context.close();
 for(const fixture of ['not json',JSON.stringify({version:1,items:[{product:'unknown',format:'art',qty:2}]}),JSON.stringify({version:1,items:[{product:'night',format:'standard',qty:2},{product:'night',format:'standard',qty:2}]}),JSON.stringify({version:1,items:[{product:'night',format:'standard',qty:1.5}]})]){
  const c=await browser.newContext();const p=await c.newPage();watch(p);await p.addInitScript(({key,fixture})=>localStorage.setItem(key,fixture),{key,fixture});await p.goto(base+'/side-b-demo.html');assert.equal(await p.locator('#sideb-count').textContent(),'0');assert.match(await p.locator('#sideb-storage-status').textContent(),/unreadable/);await p.click('#sideb-bag-open');assert.match(await p.locator('#sideb-bag-storage').textContent(),/unreadable/);assert.equal(await p.locator('#sideb-bag-total').textContent(),'£0.00');await c.close();
 }
 check('Malformed storage recovery','Invalid JSON, unknown product, duplicate edition and fractional saved quantity reset to an empty bag with an explicit notice, including inside the active bag dialog.');
 for(const method of ['getItem','setItem']){
  const c=await browser.newContext();const p=await c.newPage();watch(p);await p.addInitScript(method=>{Storage.prototype[method]=function(){throw new DOMException('Storage disabled',method==='getItem'?'SecurityError':'QuotaExceededError')}},method);await p.goto(base+'/side-b-demo.html');await p.locator('[data-product="soft"]').first().click();await p.selectOption('#sideb-format','art');await p.fill('#sideb-quantity','2');await p.locator('#sideb-product-form button[type=submit]').click();assert.match(await p.locator('#sideb-product-status').textContent(),/This visit only/);await p.click('#sideb-product-view-bag');assert.equal(await p.locator('#sideb-bag-total').textContent(),'£68.00');assert.match(await p.locator('#sideb-bag-storage').textContent(),/unavailable/);await c.close();
 }
 check('Unavailable storage fallback','SecurityError on read and QuotaExceededError on write retain an in-memory bag; 2 Soft Static art editions total £68; honest visit-only messaging inside active dialogs.');
 const reduced=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce',hasTouch:true,isMobile:true});const rp=await reduced.newPage();watch(rp);await rp.goto(base+'/side-b-demo.html');await rp.locator('[data-product="night"]').first().tap();await rp.locator('#sideb-gallery-detail').tap();assert.equal(await rp.locator('#sideb-gallery-detail').getAttribute('aria-pressed'),'true');assert.equal(await rp.evaluate(()=>document.getAnimations().length),0);await rp.selectOption('#sideb-format','standard');await rp.fill('#sideb-quantity','1');await rp.locator('#sideb-product-form button[type=submit]').tap();assert.match(await rp.locator('#sideb-product-status').textContent(),/Added 1/);await screenshot(rp,'side-b-product-mobile.jpg');await reduced.close();check('Touch and reduced motion','Emulated mobile touch opens product, changes detail immediately and adds record; no running animations. No physical device is claimed.');
 const contrast=(a,b)=>{const lum=hex=>{const channels=hex.match(/[a-f\d]{2}/gi).map(n=>parseInt(n,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*channels[0]+.7152*channels[1]+.0722*channels[2]};const l1=lum(a),l2=lum(b);return (Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05)};
 report.contrast=[['ink / yellow','#171715','#fff15a'],['ink / paper','#171715','#f5f3eb'],['focus / yellow','#283fc5','#fff15a'],['focus / paper','#283fc5','#f5f3eb'],['cover ink / orange','#171715','#f14b2d'],['cover yellow / blue','#fff15a','#283fc5'],['cover ink / green','#171715','#bbd6a6']].map(([pair,a,b])=>({pair,ratio:+contrast(a,b).toFixed(2)}));assert.ok(report.contrast.every(p=>p.ratio>=4.5));check('Colour pairings','Declared text and cover pairings exceed 4.5:1; focus pairings exceed 3:1. This is scoped evidence, not a WCAG conformance claim.');
 assert.equal(report.errors.length,0,JSON.stringify(report.errors));check('JavaScript and console errors','No pageerror or console error across exercised local pages and failure fixtures.');report.status='verified for local scope';
}catch(error){report.status='failed';report.failure=error.stack;console.error(error.stack);process.exitCode=1}
finally{await browser.close();fs.writeFileSync(path.join(root,'evidence/verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks.length,viewports:report.viewports.length,errorCount:report.errors.length,failure:report.failure},null,2))}
